### PR TITLE
MAYA-114979 MAYA-114731 Fix correctness issues

### LINKED ISSUE #1834: [MAYA-114979] UsdPreviewSurface export has several correctness problems
**Describe the bug**
We only recently became aware that the PreviewSurface export logic that Pixar added (but do not yet use internally, which is why we didn't notice) has three serious problems, two of which prevent materials with normal maps from rendering correctly anywhere except Apple products (because they chose to code around the problems, off-spec).

1. The normal map textures being used generally do not contain accurate profiles or colorSpace or gamma information, and therefore Hio texture reading logic believes they are sRGB, when non-floating-point-encoded normal maps are in fact universally linear.  Unless Maya has absolute control over the provenance of the textures, we therefore suggest that the exporter set `inputs:sourceColorSpace = "linear"` for the UsdUVTexture node that reads a normal map.
2. 8-bit normal map textures must be mapped into the [-1, 1] range for UsdPreviewSurface, which can only be accomplished by authoring `inputs:scale` and `inputs:bias` appropriately on the normal map reader.
3. Shader prims cannot be nested under other Shader prims.  Although this does not *currently* cause problems in UsdImaging, it is a violation of the UsdShade Object Model, and may cause problems in future.  De-nesting the texture-coord readers from the texture readers will also allow all texture readers to share the same one, producing more efficient shading.

**Steps to reproduce**
1. Export any geometry with UsdPreviewSurface shading, and a normal map
2. In 21.11 or dev branch, run `usdchecker` in the result.

**Expected behavior**
We should see no warnings from usdchecker, and the normals should look the same in usdview as they did in Maya.  In future releases, we would like to turn the three usdchecker warnings into errors.

**Additional context**
Pixar _may_ be able to help here, and hopes to at least provide a "fixup script" that will correct these problems in most cases of existing assets, but these patterns are unfortunately getting copied by others, so it would be great to get this addressed as soon as possible, and our resources are limited.

Thanks much and apologies for the trouble.

### PR DESCRIPTION
**Pull request by JGamache-autodesk**
This fixes #1834 for the last correctness problems mentioned

- Use a separate varnameStr for MaterialX since the type is not compatible with the varname used in UsdPreviewSurface
- Shared place2dTexture nodes are now shared on MaterialX export
- NodeGraph is used instead of Scope to isolate shaders by type in multi-material export
- NodeGraph boundaries are not skipped anymore by shader connections
- Cleaned-up code producing empty NodeGraphs

### CODE REVIEW

File: lib/usd/translators/shading/mtlxPreviewSurfaceWriter.cpp [hunk 1]
```diff
@@ -135,6 +129,15 @@ MtlxUsd_PreviewSurfaceWriter::MtlxUsd_PreviewSurfaceWriter(
 
         // All connections go directly to the node graph:
         if (attrPlug.isConnected()) {
+            if (!nodegraphSchema) {
```
Comment (JGamache-autodesk) [inline lib/usd/translators/shading/mtlxPreviewSurfaceWriter.cpp:132]: Just-in-time creation to reduce number of empty NodeGraph generated.

File: lib/usd/translators/shading/mtlxFileTextureWriter.cpp [hunk 2]
```diff
@@ -148,45 +150,67 @@ MtlxUsd_FileWriter::MtlxUsd_FileWriter(
...
-    // easy specialization based on UV mappings to geometries:
-    SdfPath          materialPath = GetUsdPath().GetParentPath();
-    UsdShadeMaterial materialSchema(GetUsdStage()->GetPrimAtPath(materialPath));
-    while (!materialSchema && !materialPath.IsEmpty()) {
-        materialPath = materialPath.GetParentPath();
-        materialSchema = UsdShadeMaterial(GetUsdStage()->GetPrimAtPath(materialPath));
-    }
+    SdfPath primvarReaderPath = _GetPlace2DTexturePath(depNodeFn);
+
+    if (!GetUsdStage()->GetPrimAtPath(primvarReaderPath)) {
```
Comment (JGamache-autodesk) [inline lib/usd/translators/shading/mtlxFileTextureWriter.cpp:155]: Mostly indentation since we now detect shared place2dTexture nodes. Similar to what was done in usdFileTextureWriter.cpp in the first PR of the series.

File: lib/usd/translators/shading/mtlxFileTextureWriter.cpp [hunk 3]
```diff
@@ -148,45 +150,67 @@ MtlxUsd_FileWriter::MtlxUsd_FileWriter(
...
-    } else {
-        varnameInput.Set(UsdUtilsGetPrimaryUVSetName());
-    }
+            TfStringPrintf("%s:%s", depNodeFn.name().asChar(), TrMtlxTokens->varnameStr.GetText()));
+
+        // We expose the primvar reader varnameStr attribute to the material to allow
+        // easy specialization based on UV mappings to geometries:
+        UsdPrim          materialPrim = primvarReaderSchema.GetPrim().GetParent();
+        UsdShadeMaterial materialSchema(materialPrim);
+        while (!materialSchema && materialPrim) {
```
Comment (JGamache-autodesk) [inline lib/usd/translators/shading/mtlxFileTextureWriter.cpp:169]: Here we make sure to properly connect the NodeGraph.

File: lib/usd/translators/shading/usdFileTextureWriter.cpp [hunk 4]
```diff
@@ -137,18 +137,27 @@ PxrUsdTranslators_FileTextureWriter::PxrUsdTranslators_FileTextureWriter(
...
         // We expose the primvar reader varname attribute to the material to allow
         // easy specialization based on UV mappings to geometries:
-        SdfPath          materialPath = GetUsdPath().GetParentPath();
-        UsdShadeMaterial materialSchema(GetUsdStage()->GetPrimAtPath(materialPath));
-        while (!materialSchema && !materialPath.IsEmpty()) {
-            materialPath = materialPath.GetParentPath();
-            materialSchema = UsdShadeMaterial(GetUsdStage()->GetPrimAtPath(materialPath));
+        UsdPrim          materialPrim = primvarReaderShaderSchema.GetPrim().GetParent();
+        UsdShadeMaterial materialSchema(materialPrim);
+        while (!materialSchema && materialPrim) {
```
Comment (JGamache-autodesk) [inline lib/usd/translators/shading/usdFileTextureWriter.cpp:147]: Connect all intermediate NodeGraphs.

File: lib/usd/translators/shading/mtlxFileTextureWriter.cpp [hunk 5]
```diff
@@ -148,45 +150,67 @@ MtlxUsd_FileWriter::MtlxUsd_FileWriter(
...
-    // input of the UV texture.
-    texSchema.CreateInput(TrMtlxTokens->texcoord, SdfValueTypeNames->Float2)
-        .ConnectToSource(primvarReaderOutput);
+        // TODO: Handle UV SRT with a ND_place2d_vector2 node. Make sure the name derives from the
+        //       place2dTexture node if there is one (see usdFileTextureWriter for details)
+
+        // Connect the output of the primvar reader to the texture coordinate
+        // input of the UV texture.
+        texSchema.CreateInput(TrMtlxTokens->texcoord, SdfValueTypeNames->Float2)
+            .ConnectToSource(primvarReaderOutput);
```
Comment (boudrey) [inline lib/usd/translators/shading/mtlxFileTextureWriter.cpp:212]: Line 206-212 could be taken out of the if/else block instead of having a duplication of code.

**Review by boudrey — APPROVED** [review]

**Comment by spiffmon** [comment]
Fantastic - thank you so much!
